// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1AL6D0GiWT4__0D0N1UWKjELcTyMLSKY',
    appId: '1:641685475143:android:050d9f830aaea5b09c0662',
    messagingSenderId: '641685475143',
    projectId: 'kaambolo-5d8c3',
    storageBucket: 'kaambolo-5d8c3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD4I6DdVH184UlleaeffpDiFfZVCNAFB0',
    appId: '1:641685475143:ios:37e715da70d329eb9c0662',
    messagingSenderId: '641685475143',
    projectId: 'kaambolo-5d8c3',
    storageBucket: 'kaambolo-5d8c3.firebasestorage.app',
    iosBundleId: 'com.kaambolo.kaamBoloMobile',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACjlYNbwUB9ewFIjh721CZpukw0mqYpaI',
    appId: '1:641685475143:web:a6622856ead1408b9c0662',
    messagingSenderId: '641685475143',
    projectId: 'kaambolo-5d8c3',
    authDomain: 'kaambolo-5d8c3.firebaseapp.com',
    storageBucket: 'kaambolo-5d8c3.firebasestorage.app',
  );
}
